### ISSUE TITLE
Issues when replacing matches in the start and end of the string

### ISSUE THREAD

**Issue by heinzmuller** [iansinnott/react-string-replace#3]
When you replace a match in the beginning/end of a string you get an extra empty item in the array which then fails subsequent requests to `reactStringReplace`

```js
let text = reactStringReplace('[player:1] versus [player:2]', /\[player:(\d+)\]/g, (match, i) => (
  <span key={i}>Player {match}</span>
));
```

Returns `["", Object, " versus ", Object, ""]` which hinders further chaining since it fails if first item in array is "empty"

**Comment by iansinnott** [comment]
Hm, thanks for the issue @heinzmuller. Let me see if I can repro

**Comment by iansinnott** [comment]
I think this might be the same as #4. 2eebd4f might address this. @heinzmuller if you upgrade to the latest release and are still seeing errors please let me know.

**Comment by heinzmuller** [comment]
@iansinnott Seems to be the same issue, will test later today and get back to you :)

**Comment by heinzmuller** [comment]
@iansinnott Sorry for the late reply, I have tested today and for my use cases it now works as expected, thanks!

**Comment by iansinnott** [comment]
Glad to hear it 👍

**Comment by djibarian** [comment]
I’m having a similar issue with 0.4.2. Getting an empty string at the end of the array replacing only one item at the end of the string: `'published {relativeTime}'` returns `['published', Object, '']`.
