### ISSUE TITLE
Multiple matches

### ISSUE THREAD

**Issue by Albert0405** [iansinnott/react-string-replace#34]
How can i make multiple matches in a sentence?

```
let sentence = "Hello Good Morning America"

ReplaceString(sentence, "Good" || "America", match => 
<Text style={{ color: 'violet' }}>{match}</Text>)
```

I want the final result to be, the word "Good" and "America" should have the fontColor of violet and the rest is default which is black. How can i achieve something like this? I tried the above code but the word "America" is the only being changed

**Comment by iansinnott** [comment]
I'm not sure what you're trying to achieve with the above code. `'Good' || 'America'` will simply evaluate to `'Good'`, so that is all you will end up replacing.

There's an example of multiple replacements in the docs: https://github.com/iansinnott/react-string-replace#multiple-replacements-on-a-single-string

**Comment by Albert0405** [comment]
Hi @iansinnott , im actually using React Native(Mobile Development) not React. Im not really familiar with Regular Expression but I'm using an example you provide in docs, this one:

```
const text = 'Hey @ian_sinn, check out this link https://github.com/iansinnott/ Hope to see you at #reactconf';
let replacedText;

// Match @-mentions
replacedText = reactStringReplace(replacedText, /@(\w+)/g, (match, i) => (
  <a key={match + i} href={`https://twitter.com/${match}`}>@{match}</a>
));
```

Unfortunately when i use multiple @ to different words, only the first word with @ is being replaced. For example

```
const text = 'Hey @ian_sinn and @albert_cruz, check out this link https://github.com/iansinnott/ Hope to see you at #reactconf';

replacedText = reactStringReplace(replacedText, /@(\w+)/g, (match, i) => (
  <a key={match + i} href={`https://twitter.com/${match}`}>@{match}</a>
));
```

The only word will be replace here is `@ian_sinn` but `@albert_cruz` is not

**Comment by Albert0405** [comment]
Hi, i already fixed it now. I'm not really familiar with RegExp so i googled it and i just change `/@(\w+)/g` to `/@(\w*)/g` so that it will read all words that has `@` in it not just the first one
