### ISSUE TITLE
Works with splitted element

### ISSUE THREAD

**Issue by ramjak** [iansinnott/react-string-replace#42]
After called into replace function, it will be outputting an array that causing regex evaluation to be incorrect.

```js
test('Works with splitted element', t => {
  const input = ['hey there', 'you', 'again'];
  t.deepEqual(
      replaceString(input, 'there you', x => `(${x})`),
      ['hey ', '(there you)', 'again']
  );
});
```

**Comment by iansinnott** [comment]
Hey @ramjak, yes that's correct. If you split what you're searching for it won't be picked up. This is a limitation of this approach over simple string replacement. 

Feel free to reopen or discuss further if you have thoughts on resolving this.
