### ISSUE TITLE
Typescript definitions are wrong (I think)

### ISSUE THREAD

**Issue by monsterkrampe** [iansinnott/react-string-replace#43]
I think the newly added type definitions are not quite correct (at least my otherwise correctly working code now throws type errors after upgrading).

I do something like:  
`reactStringReplace(<whatever>).filter(part => !!part)`
to drop some empty strings, because they would break some stuff afterwards.

Obviously `reactStringReplace` returns an Array of some Sort
```
  return flatten(source.map(function(x) {
    return isString(x) ? replaceString(x, match, fn) : x;
  }));
```

The return type in the type definitions is set to `JSX.Element` which extends `React.ReactElement`.
So on one hand, this can't be an Array and on the other hand it cannot even be a string.

I suppose the return Type should be at least `JSX.Element[]` or furthermore `(JSX.Element | string)[]` to capture the real return type of `reactStringReplace`.

For simplicity one could use `React.ReactChild[]` since `ReactChild` allows `ReactElement` as well as `string` or `number`. 

Correct me if I'm missing something.
I am willing to submit a pull request regarding this issue, I just wanted to ask first in case I'm wrong.

**Comment by iansinnott** [comment]
Ah yes I think you're right. The return type is an array, and it can be an array of anything. Generally it will be `Array<string | JSX.Element>` but there's enforcement of what actually goes into the array.

Yeah a PR would be great @monsterkrampe! I'd welcome your judgement as to what would be the most useful type definition in practice. I haven't worked with TS on a serious large project before.
