### ISSUE TITLE
Match is blank?

### ISSUE THREAD

**Issue by jjg77** [iansinnott/react-string-replace#46]
I'm trying this out in react native.  It finds the pattern, the index and the offset, but the 'match' is always empty.

sample string: "This is a test comment #123123"

`reactStringReplace(props.comment.body, /[#]\d+/gm, func)`

`const func = (match, index, offset) => {
    console.log('match:', match);
    console.log('index:', index);
    console.log('offset:', offset);
    return <TouchableHighlight key={match + index}><Text>{match}</Text></TouchableHighlight>;
  }`

Match is empty, but if I replace it with something hardcoded like "XXX" it will display.

**Comment by jjg77** [comment]
I had to match.toString()

**Comment by iansinnott** [comment]
@jjg77 Thanks for the update at for closing this one out!
