### ISSUE TITLE
Remove lodash

### ISSUE THREAD

**Issue by Daniel15** [iansinnott/react-string-replace#66]
Would you accept a PR that removes the lodash requirement?

 - `!isRegExp(re)` and `isString` can be replaced with `typeof re === 'string'`
 - `flatten` can be replaced with `flatMap` (as long as IE11 support is not required, but you could specify that a polyfill is needed for IE11 support)
 - `escapeRegExp` can just be inlined

**Comment by iansinnott** [comment]
Sure thing 👍 

Although it seems there's no need to drop IE11 support just for `flatMap`, since `flatten` can be rewritten in just a few lines.

**Comment by FoxxMD** [comment]
Considering lodash is [the majority of the package size](https://bundlephobia.com/result?p=react-string-replace@0.4.4) this would be a huge win!

**Comment by chadfawcett** [comment]
This can probably be closed now that #71 has been merged.

**Comment by Daniel15** [comment]
Sorry I didn't get around to submitting a PR for this. Thanks @bianzheCN for doing it :)
