### ISSUE TITLE
reactStringReplace is returning a blank string for match

### ISSUE THREAD

**Issue by JacobTheEvans** [iansinnott/react-string-replace#7]
I am having an issue below that when I run the code below a match is found but an empty string is returned for the match.

//code
```js
let newStr = reactStringReplace(str, /\[img.*?]/g, (match, i) => (
  <img key={"processed: " + match + i} src={match.replace('[img src="', " ").replace('"]', "")} />
));
```

//input

`[img src="http://i.imgur.com/GBpbHPh.png"]`

Any advice?

**Comment by iansinnott** [comment]
Hm, that's odd. Definitely sounds like a bug. I'd love to add a test for this to keep it from happening again. I'm not sure off hand what the issue might be but I'm happy to help out. Could you create a repo where I can reproduce this?

**Comment by JacobTheEvans** [comment]
After more experimenting, I realized it was an issue with my regex pattern. So I will close this issues sorry about that.
