### ISSUE TITLE
Cannot read property "length" of undefined

### ISSUE THREAD

**Issue by Kosurij** [iansinnott/react-string-replace#74]
If you pass a regExp as second argument in function `reactStringReplace` you can get error like: `Cannot read property "length" of undefined`. I think thiss is caused by the work of  vanilla `replace `method.

For example, this code give us an error (it's cyrillic):
const str = 'Справка Форма Ф9';
const re = /(справка[а-я]*.?(по)? форм[а-я]* [ф|Ф]\d)/gi
console.log(str.split(re));   // ["", "Справка Форма Ф9", undefined, ""]

So you cannot get length proprty of undefined. And this error will crush you page.
![Example_of_undefined](https://user-images.githubusercontent.com/62155518/147227299-e8859a80-71ad-47e0-b6fa-7d51bb0321b8.png)

**Comment by Kosurij** [comment]
My solution - [https://github.com/iansinnott/react-string-replace/pull/75](url)

**Comment by alex-clear** [comment]
Have the same issue with next Regex: `/({phone})|({name})/gi`
Then `var result = str.split(re);`  - provides next result: [`'Please enter the code we sent to you at  ', '{phone}', undefined, '', undefined, '{name}', '.            ']`

The solution for this can be next fix:  `var result = str.split(re).filter(Boolean);`
@iansinnott Can you fix this one?

**Comment by iansinnott** [comment]
what's the `str` value?

**Comment by iansinnott** [comment]
I think your regex is not doing what you expect. try using only one matching group with `|` to separate alternative matches.

Use https://regex101.com/ for quick iteration testing regex

**Comment by alex-clear** [comment]
@iansinnott Thanks for remark. You are right, there was an issue with our regex
however, IMO, in order to prevent error throws, better to add the solution above(or in existed PR), or to add try catch to the code(maybe return error with 'wrong regex provided' or something similar)

**Comment by mermail** [comment]
Yes, that does seem like unexpected behavior and the error message does not make sense unless you understand the internals. Will publish in next version.

**Comment by iansinnott** [comment]
Agreed, I pushed a change that should fix this. Thanks for raising the issue. Will publish in next version.
