### ISSUE TITLE
ReactNodeArray is deprecated

### ISSUE THREAD

**Issue by johnbonds** [iansinnott/react-string-replace#80]
per react:
    /**
     * @deprecated Use either `ReactNode[]` if you need an array or `Iterable<ReactNode>` if its passed to a host component.
     */

Possible to refactor?

**Comment by DerGoogler** [comment]
> per react: /** * @deprecated Use either `ReactNode[]` if you need an array or `Iterable<ReactNode>` if its passed to a host component. */
> 
> Possible to refactor?

You can use `(<div>Hi!</div>) as React.Node[]`

But I fixed that in my PR #81

**Comment by iansinnott** [comment]
#88
